#!/usr/bin/env python3
"""
PPT Master — 多平台适配文件生成器

从规范源 skills/ppt-master/ 生成各 AI 工具的适配文件。

用法：
    python3 build_adapters.py          # 生成所有适配
    python3 build_adapters.py claude    # 只生成 Claude Code
    python3 build_adapters.py cursor    # 只生成 Cursor
    python3 build_adapters.py windsurf  # 只生成 Windsurf
    python3 build_adapters.py agents    # 只生成 AGENTS.md
    python3 build_adapters.py gemini    # 只生成 GEMINI.md
    python3 build_adapters.py agent-sdk # 只生成 .agent/ 工作流
"""

import os
import sys
import shutil
from pathlib import Path
from datetime import datetime

# 项目根目录
ROOT = Path(__file__).parent
SKILL_DIR = ROOT / "skills" / "ppt-master"
REFS_DIR = SKILL_DIR / "references"

GENERATED_HEADER = (
    "<!-- AUTO-GENERATED by build_adapters.py — DO NOT EDIT MANUALLY -->\n"
    f"<!-- Source: skills/ppt-master/ | Generated: {datetime.now().strftime('%Y-%m-%d')} -->\n\n"
)


def read_file(path: Path) -> str:
    """读取文件内容"""
    return path.read_text(encoding="utf-8")


def write_file(path: Path, content: str):
    """写入文件，自动创建目录"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"  [OK] {path.relative_to(ROOT)}")


def read_skill_md() -> str:
    """读取 SKILL.md"""
    return read_file(SKILL_DIR / "SKILL.md")


def read_all_references() -> dict[str, str]:
    """读取所有 reference 文件，返回 {文件名: 内容}"""
    refs = {}
    for f in sorted(REFS_DIR.glob("*.md")):
        refs[f.name] = read_file(f)
    return refs


def adapt_paths_for_root(content: str) -> str:
    """将 skill 内部路径适配为仓库根目录视角"""
    replacements = {
        "${SKILL_DIR}/scripts/": "skills/ppt-master/scripts/",
        "${SKILL_DIR}/templates/": "skills/ppt-master/templates/",
        "${SKILL_DIR}/": "skills/ppt-master/",
        "references/": "skills/ppt-master/references/",
    }
    for old, new in replacements.items():
        content = content.replace(old, new)
    return content


def adapt_paths_for_claude(content: str) -> str:
    """将 skill 内部路径适配为 .claude/skills/ 视角"""
    # Claude Code 的 skill 路径是相对于 .claude/skills/ppt-master/
    # 脚本和模板在 skills/ppt-master/ 下，需要用 ../../../skills/ppt-master/
    replacements = {
        "${SKILL_DIR}/scripts/": "../../../skills/ppt-master/scripts/",
        "${SKILL_DIR}/templates/": "../../../skills/ppt-master/templates/",
        "${SKILL_DIR}/": "../../../skills/ppt-master/",
    }
    for old, new in replacements.items():
        content = content.replace(old, new)
    return content


# ============================================================
# 适配器：Claude Code
# ============================================================
def build_claude():
    """生成 .claude/skills/ppt-master/"""
    print("\n[Claude Code] 生成 .claude/skills/ppt-master/")
    out_dir = ROOT / ".claude" / "skills" / "ppt-master"

    # 复制 SKILL.md（路径适配）
    skill_content = read_skill_md()
    skill_content = adapt_paths_for_claude(skill_content)
    write_file(out_dir / "SKILL.md", GENERATED_HEADER + skill_content)

    # 复制 references/
    refs_out = out_dir / "references"
    for f in sorted(REFS_DIR.glob("*.md")):
        content = read_file(f)
        write_file(refs_out / f.name, content)


# ============================================================
# 适配器：Cursor
# ============================================================
def build_cursor():
    """生成 .cursor/rules/ppt-master.md — 合并为单文件"""
    print("\n[Cursor] 生成 .cursor/rules/ppt-master.md")
    refs = read_all_references()

    parts = [GENERATED_HEADER]
    parts.append("# PPT Master — AI 驱动的 SVG 内容生成系统\n\n")
    parts.append("> 本文件由 `build_adapters.py` 从 `skills/ppt-master/` 自动生成。\n\n")

    # SKILL.md 的核心流程部分
    skill = read_skill_md()
    skill = adapt_paths_for_root(skill)
    # 去掉 YAML frontmatter
    if skill.startswith("---"):
        end = skill.find("---", 3)
        if end != -1:
            skill = skill[end + 3:].strip()
    parts.append(skill)
    parts.append("\n\n---\n\n")

    # 按顺序合并 references
    ref_order = [
        "shared-standards.md",
        "canvas-formats.md",
        "design-guidelines.md",
        "strategist.md",
        "image-generator.md",
        "executor-base.md",
        "executor-general.md",
        "executor-consultant.md",
        "executor-consultant-top.md",
        "optimizer-crap.md",
        "template-designer.md",
        "image-layout-spec.md",
        "svg-image-embedding.md",
    ]

    for name in ref_order:
        if name in refs:
            content = refs[name]
            content = adapt_paths_for_root(content)
            # 去掉引用其他 reference 的行（在合并文件中不需要）
            lines = content.split("\n")
            lines = [l for l in lines if not l.startswith("> 📎")]
            content = "\n".join(lines)
            parts.append(f"\n---\n\n")
            parts.append(content)

    write_file(ROOT / ".cursor" / "rules" / "ppt-master.md", "".join(parts))


# ============================================================
# 适配器：Windsurf
# ============================================================
def build_windsurf():
    """生成 .windsurf/rules/ppt-master.md — 与 Cursor 格式类似"""
    print("\n[Windsurf] 生成 .windsurf/rules/ppt-master.md")
    # Windsurf 格式与 Cursor 基本相同
    refs = read_all_references()

    parts = [GENERATED_HEADER]
    parts.append("# PPT Master — AI 驱动的 SVG 内容生成系统\n\n")
    parts.append("> 本文件由 `build_adapters.py` 从 `skills/ppt-master/` 自动生成。\n\n")

    skill = read_skill_md()
    skill = adapt_paths_for_root(skill)
    if skill.startswith("---"):
        end = skill.find("---", 3)
        if end != -1:
            skill = skill[end + 3:].strip()
    parts.append(skill)
    parts.append("\n\n---\n\n")

    ref_order = [
        "shared-standards.md",
        "canvas-formats.md",
        "design-guidelines.md",
        "strategist.md",
        "image-generator.md",
        "executor-base.md",
        "executor-general.md",
        "executor-consultant.md",
        "executor-consultant-top.md",
        "optimizer-crap.md",
        "template-designer.md",
        "image-layout-spec.md",
        "svg-image-embedding.md",
    ]

    for name in ref_order:
        if name in refs:
            content = refs[name]
            content = adapt_paths_for_root(content)
            lines = content.split("\n")
            lines = [l for l in lines if not l.startswith("> 📎")]
            content = "\n".join(lines)
            parts.append(f"\n---\n\n")
            parts.append(content)

    write_file(ROOT / ".windsurf" / "rules" / "ppt-master.md", "".join(parts))


# ============================================================
# 适配器：AGENTS.md（通用单文件）
# ============================================================
def build_agents():
    """生成 AGENTS.md — 通用单文件完整指南"""
    print("\n[AGENTS.md] 生成通用单文件指南")
    refs = read_all_references()

    parts = [GENERATED_HEADER]
    parts.append("# AGENTS.md — PPT Master 完整指南\n\n")
    parts.append("> ⚠️ **AI 代理注意**：本文件是 PPT 生成流程的完整指南。\n")
    parts.append("> 本文件由 `build_adapters.py` 从 `skills/ppt-master/` 自动生成，请勿手动编辑。\n\n")

    # 工作流部分（从 SKILL.md 提取，路径适配）
    skill = read_skill_md()
    skill = adapt_paths_for_root(skill)
    # 去掉 frontmatter
    if skill.startswith("---"):
        end = skill.find("---", 3)
        if end != -1:
            skill = skill[end + 3:].strip()
    parts.append(skill)
    parts.append("\n\n---\n\n")
    parts.append("# 详细参考\n\n")
    parts.append("以下内容为各角色和技术规范的详细说明。\n\n")

    # 合并 references
    ref_order = [
        ("shared-standards.md", "公共技术约束"),
        ("canvas-formats.md", "画布格式规范"),
        ("design-guidelines.md", "设计指南"),
        ("strategist.md", "Strategist 角色定义"),
        ("image-generator.md", "Image_Generator 角色定义"),
        ("executor-base.md", "Executor 公共准则"),
        ("executor-general.md", "Executor — General 风格"),
        ("executor-consultant.md", "Executor — Consultant 风格"),
        ("executor-consultant-top.md", "Executor — Consultant_Top 风格"),
        ("optimizer-crap.md", "Optimizer_CRAP 角色定义"),
        ("template-designer.md", "Template_Designer 角色定义"),
        ("image-layout-spec.md", "图片布局规范"),
        ("svg-image-embedding.md", "SVG 图片嵌入技术"),
    ]

    for name, title in ref_order:
        if name in refs:
            content = refs[name]
            content = adapt_paths_for_root(content)
            # 去掉引用行
            lines = content.split("\n")
            lines = [l for l in lines if not l.startswith("> 📎")]
            content = "\n".join(lines)
            parts.append(f"\n---\n\n")
            parts.append(content)

    write_file(ROOT / "AGENTS.md", "".join(parts))


# ============================================================
# 适配器：CLAUDE.md
# ============================================================
def build_claude_md():
    """生成 CLAUDE.md — Claude Code 项目指南（精简版）"""
    print("\n[CLAUDE.md] 生成 Claude Code 项目指南")

    content = GENERATED_HEADER + """# CLAUDE.md

本文件为 Claude Code 提供项目概览。完整规则见 `skills/ppt-master/` 或 `AGENTS.md`。

## 项目概述

PPT Master 是一个 AI 驱动的多格式 SVG 内容生成系统。通过多角色协作（Strategist → Image_Generator → Executor → Optimizer），将源文档（PDF/URL/Markdown）转化为高质量 SVG 页面，并导出为 PPTX。

**核心流程**：`源文档 → 创建项目 → 模板选项 → Strategist八项确认 → [Image_Generator] → Executor → 后处理 → 导出PPTX`

**Skill 模式**：如已安装 skill，使用 `/ppt` 命令进入交互式流程。

**完整工作流和规则手册**：执行 PPT 生成任务前，必须阅读 [AGENTS.md](./AGENTS.md)。

## 常用命令

```bash
# 源内容转换
python3 skills/ppt-master/scripts/pdf_to_md.py <PDF文件>
python3 skills/ppt-master/scripts/web_to_md.py <URL>
node skills/ppt-master/scripts/web_to_md.cjs <URL>

# 项目管理
python3 skills/ppt-master/scripts/project_manager.py init <项目名> --format ppt169
python3 skills/ppt-master/scripts/project_manager.py validate <项目路径>

# 图片工具
python3 skills/ppt-master/scripts/analyze_images.py <项目路径>/images
python3 skills/ppt-master/scripts/nano_banana_gen.py "提示词" --aspect_ratio 16:9 --image_size 4K -o <项目路径>/images

# SVG 质量检查
python3 skills/ppt-master/scripts/svg_quality_checker.py <项目路径>

# 后处理三步（必须按顺序执行）
python3 skills/ppt-master/scripts/total_md_split.py <项目路径>
python3 skills/ppt-master/scripts/finalize_svg.py <项目路径>
python3 skills/ppt-master/scripts/svg_to_pptx.py <项目路径> -s final
```

## 架构

- `skills/ppt-master/references/` — AI 角色定义和技术规范
- `skills/ppt-master/scripts/` — 28个工具脚本
- `skills/ppt-master/templates/` — 布局模板、图表模板、640+ 矢量图标
- `examples/` — 示例项目
- `build_adapters.py` — 多平台适配文件生成器

## SVG 技术约束（不可协商）

**禁用功能**：`clipPath` | `mask` | `<style>` | `class/id` | 外部 CSS | `<foreignObject>` | `textPath` | `@font-face` | `<animate*>` | `<script>` | `marker-end` | `<iframe>` | `<symbol>+<use>`

**PPT 兼容性替代**：

| 禁止 | 替代 |
|------|------|
| `rgba()` | `fill-opacity` / `stroke-opacity` |
| `<g opacity>` | 每个子元素单独设置 opacity |
| `<image opacity>` | 遮罩层叠加 |
| `marker-end` 箭头 | `<polygon>` 三角形 |

## 画布格式速查

| 格式 | viewBox |
|------|---------|
| PPT 16:9 | `0 0 1280 720` |
| PPT 4:3 | `0 0 1024 768` |
| 小红书 | `0 0 1242 1660` |
| 朋友圈 | `0 0 1080 1080` |
| Story | `0 0 1080 1920` |

## 后处理注意事项

- **禁止**用 `cp` 命令替代 `finalize_svg.py`
- **禁止**从 `svg_output/` 直接导出，必须从 `svg_final/`（`-s final`）导出
- 后处理三步命令不要添加 `--only` 等额外参数
"""

    write_file(ROOT / "CLAUDE.md", content)


# ============================================================
# 适配器：GEMINI.md
# ============================================================
def build_gemini():
    """生成 GEMINI.md"""
    print("\n[GEMINI.md] 生成 Gemini 指南")
    content = GENERATED_HEADER + """# GEMINI.md

> **本文件内容与 [AGENTS.md](./AGENTS.md) 保持同步，请以 AGENTS.md 为准。**

请阅读 [AGENTS.md](./AGENTS.md) 获取完整的 AI 代理协作指引。
"""
    write_file(ROOT / "GEMINI.md", content)


# ============================================================
# 适配器：Agent SDK
# ============================================================
def build_agent_sdk():
    """生成 .agent/workflows/"""
    print("\n[Agent SDK] 生成 .agent/workflows/")

    # generate-ppt.md
    content = GENERATED_HEADER + """---
description: 从 Markdown 源文档生成 PPT 的完整流程（主入口）
---

# PPT 生成工作流

> 本文件由 `build_adapters.py` 自动生成。

**完整流程**请参阅 [AGENTS.md](../../AGENTS.md)，该文件包含完整的工作流程和规则手册。

**快速跳转**：
- [工作流程](../../AGENTS.md#工作流) — 从源文档到 PPT 的完整执行步骤
- [详细参考](../../AGENTS.md#详细参考) — 各角色定义和技术规范
"""
    write_file(ROOT / ".agent" / "workflows" / "generate-ppt.md", content)

    # create-template.md — 保留已有内容但更新路径
    template_workflow = ROOT / ".agent" / "workflows" / "create-template.md"
    if template_workflow.exists():
        content = read_file(template_workflow)
        # 更新角色引用路径
        content = content.replace(
            "../roles/Template_Designer.md",
            "../../skills/ppt-master/references/template-designer.md"
        )
        content = content.replace(
            'templates/layouts/',
            'skills/ppt-master/templates/layouts/'
        )
        write_file(template_workflow, content)


# ============================================================
# 主入口
# ============================================================
ADAPTERS = {
    "claude": build_claude,
    "cursor": build_cursor,
    "windsurf": build_windsurf,
    "agents": build_agents,
    "claude-md": build_claude_md,
    "gemini": build_gemini,
    "agent-sdk": build_agent_sdk,
}


def build_all():
    """生成所有适配文件"""
    print(f"PPT Master — 多平台适配文件生成器")
    print(f"规范源: {SKILL_DIR.relative_to(ROOT)}/")
    print(f"生成时间: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

    for name, builder in ADAPTERS.items():
        builder()

    print(f"\n[DONE] 全部完成！共生成 {len(ADAPTERS)} 个适配。")


def main():
    if len(sys.argv) < 2:
        build_all()
    else:
        target = sys.argv[1].lower()
        if target == "all":
            build_all()
        elif target in ADAPTERS:
            ADAPTERS[target]()
            print(f"\n[DONE] {target} 适配生成完成。")
        else:
            print(f"未知目标: {target}")
            print(f"可用目标: {', '.join(ADAPTERS.keys())}, all")
            sys.exit(1)


if __name__ == "__main__":
    main()
